# Generated by Django 4.1.5 on 2025-04-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='link',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='menuname',
            old_name='link',
            new_name='slug',
        ),
    ]
